### PR TITLE
Add daily refraction correction function

### PR DESCRIPTION
**Pull request by binchensun**
- Giving a day, process all level 1 FITS files into level 1.5 by deriving and applying refraction corrections. Do interpolation for failed frames. Then, compress FITS files to HDF files and save them. 
- Small feature of including an optional --bmfit_sz in the call. Default to 2.

### CODE REVIEW

**Review by surajit4444mondal — COMMENTED** [review]
We are now using horizon-mask 5deg in the default call of run_wsclean.  This stops WSClean cleaning RFI and going to CLEAN instabilities. I suggest that we add this in default_wscleancmd as well.

**Comment by binchensun** [comment]
Good point. I'll add it.

**Comment by binchensun** [comment]
Added "-horizon-mask 5deg" with the new commit.

**Review by peijin94 — APPROVED** [review]
changes looks good to me

**Pull request merged**
