### PR TITLE
Implement slurm

### PR DESCRIPTION
**Pull request by peijin94**

### CODE REVIEW

**Comment by surajit4444mondal** [comment]
Can we put this onto a separate branch and test on realtime data first?

**Comment by peijin94** [comment]
Tested working for realtime observation, ready to merge

**Comment by peijin94** [comment]
implemented daily refraction correction as a standalone slurm task, will test with one day or two observation

**Comment by surajit4444mondal** [comment]
@peijin94 Is this updated? We can then merge these changes

**Comment by surajit4444mondal** [comment]
Approving based on the fact that it has been running for many days  now

**Review by surajit4444mondal — APPROVED** [review]

**Pull request merged**
